INSERT INTO USUARIO(NAME,EMAIL,PASSWORD) VALUES('mestre','mestre@EMAIL.com','degas');
INSERT INTO USUARIO(NAME,EMAIL,PASSWORD) VALUES('zangado','zangado@EMAIL.com','degas');
INSERT INTO USUARIO(NAME,EMAIL,PASSWORD) VALUES('atchim','atchim@EMAIL.com','degas');
INSERT INTO USUARIO(NAME,EMAIL,PASSWORD) VALUES('soneca','soneca@EMAIL.com','degas');