INSERT INTO PILOTO(NOME,NUM_BREVE) VALUES ('Joao','123');
INSERT INTO PILOTO(NOME,NUM_BREVE) VALUES ('Paulo','148');
INSERT INTO PILOTO(NOME,NUM_BREVE) VALUES ('Ricardo','152');
INSERT INTO PILOTO(NOME,NUM_BREVE) VALUES ('Pedro','323');
INSERT INTO PILOTO(NOME,NUM_BREVE) VALUES ('Laio','554');

INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('AirTech', 'Modelo A');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('SkyWings', 'Modelo B');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('AeroDynamics', 'Modelo C');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('AviaNova', 'Modelo D');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('JetMasters', 'Modelo E');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('Boeing', '737');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('Airbus', 'A320');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('Embraer', 'E190');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('Bombardier', 'CRJ900');
INSERT INTO MODELO_AERONAVE (FABRICANTE, NOME) VALUES ('Cessna', 'Citation X');

INSERT INTO AEROPORTO (ICAO, NOME) VALUES ('JFK', 'John F. Kennedy International Airport');
INSERT INTO AEROPORTO (ICAO, NOME) VALUES ('LHR', 'London Heathrow Airport');
INSERT INTO AEROPORTO (ICAO, NOME) VALUES ('CDG', 'Charles de Gaulle Airport');
INSERT INTO AEROPORTO (ICAO, NOME) VALUES ('DXB', 'Dubai International Airport');
INSERT INTO AEROPORTO (ICAO, NOME) VALUES ('HND', 'Tokyo Haneda Airport');
